### ISSUE TITLE
PDB files should be implemented in `process_nested_docs_dict` in `doc_funcs.smk`

### ISSUE THREAD

**Issue by caelanradford** [dms-vep/dms-vep-pipeline-3#39] opened 2023-08-16 23:22 UTC
We often like to renumber the b-factors of PDB structures so that we can color them by functional effect or antibody escape. The PDB outputs of custom rules and scripts that do this cannot be passed in the docs dictionary to `process_nested_docs_dict` in `doc_funcs.smk` because that function does not currently handle PDB files. My current workaround is to just add the PDB outputs to rule all, which is not a good long term solution.

**Comment by jbloom** [comment] 2023-08-16 23:42
I'm happy to do this, my main question would just be is it important to add these to the HTML docs or can the file just be on GitHub.

Conceptually, everything (data, code, etc) is on GitHub.

The HTML docs are supposed to be an easy way to navigate the subset of things on GitHub that hold key results that might be of interest to people who don't want to look at the full analysis but want to get or visualize key results.

So in that sense, my question: is a PDB file really the type of thing that we think people who don't care enough to look at GitHub would want in the docs? Or should the docs more have something like a link to `dms-viz` that might be generated using a PDB, but the PDB really belongs in the code / data.

I would lean towards a PDB not really being something that a reader needs to look at to understand our analysis (maybe they would want a rendering of a PDB).

But if you have a good rationale why a PDB should be part of the docs rather than just on the GitHub, post it here and then I can add.

**Comment by caelanradford** [comment] 2023-08-17 00:26
The files could just be on GitHub, that is fine. It would actually be good to also implement `dms-viz` into the pipeline. 

The issue is just that I cannot get snakemake to run my custom rules that make these PDBs because they do not end up as any of the inputs into rule all, since none of their outputs end up in the docs as html files.

**Comment by jbloom** [comment] 2023-08-17 00:32
Yes, the pipeline will only make them if they are being used as an output in the pipeline or by another rule that generates and output.

**Comment by jbloom** [comment] 2023-08-18 16:52
@caelanradford, the pull request in #42 (when merged) should solve this issue.

As far as I can tell, the issue is not actually that you want to show PDB files as part of the docs, which doesn't make any sense for reasons mentioned above.

The issue is that you want to be able to make the pipeline build targets that are not part of the docs, which is reasonable.

So I have added (in #42) a `other_target_files` variable. If you add the files you want to create to the `other_target_files` list in your `custom_rules.smk` rules, then it will be built as a target of the pipeline.

**Comment by caelanradford** [comment] 2023-08-18 16:54
Yes, that is a better description of the real issue, and that should solve it. 

Thanks

**Closed** 2023-08-18 19:34 UTC
