### ISSUE TITLE
Error in multidms due to indel at end of my alignment

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep-pipeline-3#1] opened 2023-07-18 18:48 UTC
The Nipah RBP should be 602 amino acids, but there must be a small insertion in fraction of reads. This site gets identified as '602a' in the pipeline. This happened in the old dms-vep-pipeline, but it didn't cause any issues. Now it appears to be causing an issue with the multidms pipeline. See error log below:

```
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 data = multidms.MultiDmsData(
      2     variants_df=func_scores_df,
      3     reference=selection,
      4     alphabet=multidms.AAS_WITHSTOP_WITHGAP,
      5     collapse_identical_variants=global_epistasis_params["collapse_identical_variants"],
      6     letter_suffixed_sites=True,
      7     verbose=True,
      8     nb_workers=threads,
      9 )

File /fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline-3/lib/python3.11/site-packages/multidms/data.py:380, in MultiDmsData.__init__(self, variants_df, reference, alphabet, collapse_identical_variants, condition_colors, letter_suffixed_sites, assert_site_integrity, filter_non_shared_subs, verbose, nb_workers)
    378 binmaps, X, y = {}, {}, {}
    379 for condition, condition_func_score_df in df.groupby("condition"):
--> 380     ref_bmap = bmap.BinaryMap(
    381         condition_func_score_df,
    382         substitutions_col="var_wrt_ref",
    383         allowed_subs=allowed_subs,
    384         alphabet=self.alphabet,
    385     )
    386     binmaps[condition] = ref_bmap
    387     X[condition] = sparse.BCOO.from_scipy_sparse(ref_bmap.binary_variants)

File /fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline-3/lib/python3.11/site-packages/binarymap/binarymap.py:496, in BinaryMap.__init__(self, func_scores_df, substitutions_col, func_score_col, func_score_var_col, n_pre_col, n_post_col, cols_optional, alphabet, allowed_subs, sites_as_str, expand, wtseq)
    494     subs_in_variants = allowed_subs
    495 for sub in subs_in_variants:
--> 496     wt, site, mut = self._parse_sub_str(sub)
    497     if site not in wts:
    498         wts[site] = wt

File /fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline-3/lib/python3.11/site-packages/binarymap/binarymap.py:618, in BinaryMap._parse_sub_str(self, sub)
    616 m = re.fullmatch(self._sub_regex, sub)
    617 if not m:
--> 618     raise ValueError(
    619         f"substitution {sub} is invalid " f"for alphabet {self.alphabet}"
    620     )
    621 if m.group("wt") == m.group("mut"):
    622     raise ValueError(f"wildtype and mutant identity the same in {sub}")

ValueError: substitution *602aY is invalid for alphabet ('A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', '*', '-')


```

**Comment by jbloom** [comment] 2023-07-18 19:25
I will work out sorting out why the code is throwing an error.

But @bblarsen-sci, just for your clarity, this is **not** due to some of the reads having an insertion. It is instead because they way you have assigned your numbering, you have specified that site 571 in the sequential numbering should be called site 602a. If that is not what you intended, you might fix that. See the last row here:
https://github.com/dms-vep/Nipah_Malaysia_RBP_DMS_old/blob/main/results/site_numbering/site_numbering_map.csv

**Comment by jbloom** [comment] 2023-07-18 19:43
As far as the error itself (which exists regardless of whether or not the Nipah numbering scheme that caused it is correct in that particular repo), it was caused by a bug in `multidms` which will be fixed by the following pull request to that repo: https://github.com/matsengrp/multidms/pull/97

**Comment by bblarsen-sci** [comment] 2023-07-18 20:08
ah, thank you! I will change the numbering, not sure why I did that.

**Closed** 2023-07-18 21:16 UTC
